name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  MIN_COVERAGE: 0.2

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Setup Xcode Version
        shell: bash
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.2.app
      - uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.workflow }}
          restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-
      - name: Build for iOS
        shell: bash
        run: |
          xcodebuild -scheme LiveViewNativeLiveForm -destination "platform=iOS Simulator,name=iPhone 15 Pro" -skipMacroValidation -skipPackagePluginValidation
      - name: Build for macOS
        shell: bash
        run: |
          xcodebuild -scheme LiveViewNativeLiveForm -destination "platform=macOS" -skipMacroValidation -skipPackagePluginValidation
      - name: Build for watchOS
        shell: bash
        run: |
          xcodebuild -scheme LiveViewNativeLiveForm -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)" -skipMacroValidation -skipPackagePluginValidation
      - name: Build for tvOS
        shell: bash
        run: |
          xcodebuild -scheme LiveViewNativeLiveForm -destination "name=Any tvOS Device" -skipMacroValidation -skipPackagePluginValidation
